<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8" />
  <meta name="description" content="jobs" />
  <meta name="keywords" content="job, describe, job description,  job position" />
  <meta name="author" content="Tanadol Baibong"  />
  <title>Jobs</title>
    
  <link rel="stylesheet" href="styles/styles.css">
    <style>
        .look { 
            color: rgb(0, 0, 0);
            text-align: center;  
            text-decoration: underline;
            background-color: aliceblue;
            border: 10px solid aliceblue;
            border-radius: 15px;
        }

        .images {  
            display: flex;
            align-items: center;
            flex-direction: column;
            margin: 50px;
            flex-wrap: wrap;
        }

        .skills {
            font-weight: bold;
            text-decoration-line: underline;
        }

        #container {
            display: flex;
            justify-content: space-evenly;
        }

        .job { 
            font-size: 18px;
            width: 35%;
            margin: 2em;
            border: 10px groove rgb(0, 0, 0);
            background-color: rgb(255, 243, 198);
            flex-direction: column;
        }

        #architect {
            border: 2px solid black;
            border-radius: 15px;
            background-color: white;
            font-size: 35px;
            text-align: center;
            margin-bottom: 100px;
        }

        #manager {
            border: 2px solid black;
            border-radius: 15px;
            background-color: white;
            font-size: 35px;
            text-align: center;
            margin-bottom: 115px;
            
        }

        .response {
            font-weight: bold;
            text-decoration: underline;
        }

        .buttons {
            color: black;
            text-decoration:solid;
            text-align: center;
            background-color: rgb(255, 248, 248);
            border: 3px solid black;
            font-size: 20px;
            padding: 0.5em;
            cursor: pointer;
        }

        .buttons:hover {
            background-color: rgb(199, 239, 214);
        }

        aside a {
            display: flex;
            flex-direction: column;
            flex-wrap: nowrap;
            justify-content: center;
            align-items: center;
            align-content: normal;
            padding: 5em;
            border-radius: 15px;
            margin: 40px;
        }
    </style>

 </head>

 <body>

 <header id="jobhead"> 
    <h1 style="color: rgb(255, 176, 40);">Job opportunities</h1>
 </header>


 <?php include 'nav.inc'; ?>
 <?php require_once("settings.php");?>

  
 <section class="look">
 <h2>
    <em>Our Company is looking for new team members!</em><br>
    <em>Take your opportunity to apply now!</em>
 </h2>

<div class="search-bar">
    <form action="jobs.php" method="GET">
        <label for="search"><strong>Search Jobs: </strong></label>
        <input type="text" name="search" id="search" placeholder="Search by title or keyword...">
        <button type="submit">Search</button>
    </form>
 </div>

 </section>
 <div id="container">
 <aside id="Page" class="job">
<h1 id="architect">
    <strong>Smart Grid Architecture</strong>
</h1>
 <p id="job1des"><strong>Job Description:</strong> The Smart Grid Architect focuses on the intersection of energy and digital infrastructure.<br> 
    You will design the technical frameworks for modernising power distribution, integrating distributed energy resources (DERs)<br> 
    like solar and wind, and enabling two-way communication between the grid and smart meters for real-time monitoring and demand response.</p>
  
    <img class="images" src="images/Smart_grid.png" alt="smart" width="300" height="400">
    <!-- This image generated by Gemini 3.1 Pro -->
    
    <ul>
    <li>Reference: SG612</li>
    <li>Salary: $155,000–$195,000 AUD</li>
    <li>Reporting Line: Director of Energy Systems</li>

</ul>
    
    <p class="response">Key Responsibilities</p>
<ol>
    <li>Designing end-to-end technical architectures for urban IoT deployments.</li>
    <li>Ensuring interoperability between legacy city infrastructure and new digital platforms.</li>
    <li>Conducting impact assessments to measure the ROI of smart technology investments.</li>
    <li>Cleaning and managing "Big Data" sets to ensure accuracy in automated city services.</li>
</ol>

<!-- This job generated by Gemini 3.1 Pro -->

 <p class="skills">Required Skills</p>
<ol>
    <li><strong>Essential:</strong> Degree in Electrical Engineering or Power Systems; 5+ years in power systems design; expertise in SCADA systems.</li>
    <li><strong>Preferable:</strong> Experience with IEEE 2030.5 standards; BESS (Battery Energy Storage) experience.</li>
</ol>
 <a href="apply.html" class="buttons">Click here to apply</a>
</aside>


<aside id="Page" class="job">
    <h1 id="manager">
    <strong>Project Manager</strong>
</h1>
 <p id="job2des"><strong>Job Description:</strong> You will lead the end-to-end delivery of digital platforms for councils and industry partners. 
    This role involves managing the deployment of smart transport  and energy monitoring systems, ensuring projects are completed on time, within budget, 
    and meet the specific urban needs of Australian communities.

    <img class="images" src="images/projectmanager.png" alt="manager" width="300" height="400">
    <!-- This image generated by Gemini 3.1 Pro -->
    
    <ul>
    <li>Reference: PM305</li>
    <li>Salary: $130,000–$165,000 AUD.</li>
    <li>Reporting Line: Head of Operations</li>

</ul>
    
    <p class="response">Key Responsibilities</p>
<ol>
    <li>Manage the project lifecycle for urban services management platforms</li>
    <li>Act as the primary point of contact for council stakeholders and technology vendors.</li>
    <li>Track project KPIs, including budget utilization and infrastructure deployment milestones.</li>
    <li>Identify and mitigate risks related to physical hardware installation and software integration.</li>
</ol>

 <p class="skills">Required Skills</p>
<ol>
    <li><strong>Essential:</strong> Degree in Project Management, Business, or IT; 3+ years experience in infrastructure or technology projects; PMBOK or PRINCE2 certification.</li>
    <li><strong>Preferable:</strong> Experience working with Australian local government procurement; background in IoT or smart city technologies; strong contract negotiation skills.</li>
</ol>
<!-- This job generated by Gemini 3.1 Pro -->
 <a href="apply.html" class="buttons">Click here to apply</a>
 </aside>
</div>
 <?php include 'footer.inc'; ?>
</body>


   </html>

 
